name: "Build and test"
on:
  pull_request:
  push:
jobs:

  build:
    strategy: 
      matrix: 
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix show-config
    - run: nix-env -f '<nixpkgs>' -i nix-build-uncached
    - run: nix-build-uncached --argstr git-rev $(git rev-parse HEAD) default.nix
    - run: nix-build-uncached --argstr git-rev $(git rev-parse HEAD) -j16 -build-flags '--option sandbox relaxed' integration-tests/default.nix
      if: matrix.os == 'ubuntu-latest'
    - run: nix-shell --run "echo OK"

  build-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: docker login --username botstrom --password "$DOCKER_HUB_ACCESS_TOKEN"
      if: github.ref == 'refs/heads/main'
      env:
        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - run: docker load -i $(nix-build --argstr git-rev $(git rev-parse HEAD) docker.nix)
    - run: |
        version=$(grep '^version' cli/quickstrom-cli.cabal  | cut -d':' -f2 | xargs)
        docker tag quickstrom/quickstrom:latest quickstrom/quickstrom:$version
        docker push quickstrom/quickstrom:latest
        docker push quickstrom/quickstrom:$version
      if: github.ref == 'refs/heads/main'
